### PR TITLE
Split repository to support Multiple languages

### PR DESCRIPTION
**Pull request by tebeco**
Split repository to support Multiple languages

First commit for C# in .Net Core 1.0 RTM 
- VS2015 update 3 + Net core SDK is mandatory to open in Visual Studio
- Maybe working in VsCore (updated) + C# extension (not tested)

### CODE REVIEW

**Comment by alexvictoor** [comment]
Thanks for the PR
Please move back .travis.yml file at the root of the repository and update inside this file the path to m

**Comment by alexvictoor** [comment]
Thanks for the PR
Please move back .travis.yml file at the root of the repository and update inside this file the path to maven pom.xml files

**Comment by flegall** [comment]
Thanks for the PR !
Yes, moving back the main travis.yml and prefixing paths there should do the trick.

**Comment by tebeco** [comment]
Closing ... Creating another repo ... Probably

**Comment by alexvictoor** [comment]
Too bad ! I guess everything in a single repo would be simpler on the long run

**Comment by tebeco** [comment]
I thought you wanted to create a new repo with AppVeyor etc ... inside "RxHandsOn" organisation last friday

**Comment by tebeco** [comment]
Ok i did not see the previous msg, I'll change that

**Comment by tebeco** [comment]
Did not see*

**Comment by tebeco** [comment]
Ok this one is funny ;)

**Comment by tebeco** [comment]
So the "Buffer size" was to 70 ... i'm just stupid. The Replay Buffer seems to works.

But stil there's an issue, there's 50% of chance to have a HUGE latency on connection.
Even a breakpoint on the first line of the Kestrel Middleware takes 3 to 10 sec to be catch, my guess is that there's really dirty lock/hang on my first attempt to use Kestrel for the Implementation of the SSE server.

I can't figure out yet why the first line of the Kestrel handler is having a bad time

**Pull request closed without merging**
